added app.py checks inside CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -41,6 +41,12 @@ jobs:
       - name: Run Unit Tests
         run: |
           python -m unittest discover -s . -p "test_*.py"
+      
+      - name: Check app.py launches successfully
+        run: |
+          timeout 5s python app.py &
+          sleep 3
+          curl -I http://127.0.0.1:5000 || (echo "❌ app.py failed to respond" && exit 1)
 
       - name: Show test result status
         if: ${{ failure() }}
